version: 2

updates: 
  # Enable version updates for NuGet.
  - package-ecosystem: "nuget"
    # Look for NuGet dependency info from the solution directory.
    directory: "/Acolyte.NET"
    # Check the nuget registry for updates every day (weekdays).
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
