version: 2

updates: 
  # Enable version updates for NuGet.
  - package-ecosystem: "nuget"
    # Look for NuGet dependency info from the solution directory.
    directory: "/Acolyte.NET"
    # Check the nuget registry for updates: daily/weekly/monthly.
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    # Specify additional information for NuGet pull requests.
    labels:
      - "area: Dependencies"
      - "type: Code Maintenance"
      - "status: External"
    assignees:
      - "Vasar007"
    reviewers:
      - "Vasar007"
    # Raise pull requests for version updates
    # to NuGet against the "develop" branch.
    target-branch: "develop"
