environment:
  packageVersion: 2.2.0
  acolytePackageZip: 'Acolyte.NET.$(packageVersion).zip'

version: '$(packageVersion).{build}'
image: Visual Studio 2022

# Do not build on tags (GitHub, Bitbucket, GitLab, Gitea).
skip_tags: true

shallow_clone: true

dotnet_csproj:
  patch: true
  file: '**\*.csproj;**\*.fsproj'
  assembly_version: '$(packageVersion)'
  file_version: '$(packageVersion)'
  version: '$(packageVersion)'

# All branches are built by default.

# Build platform is used from solution settings.

configuration:
  - Debug
  - Release

matrix:
  fast_finish: true

before_build:
  - ps: dotnet restore Acolyte.NET

# Build only package solution. Samples solution will not be built by CI now.
build:
  project: Acolyte.NET
  verbosity: minimal

after_build:
  - ps: >-
      if (($env:configuration -eq "Release") -and ($env:APPVEYOR_REPO_BRANCH -eq "master"))
      {
        dotnet pack --configuration Release --no-build "Acolyte.NET"
        7z a -tzip "$env:APPVEYOR_BUILD_FOLDER/$env:acolytePackageZip" "$env:APPVEYOR_BUILD_FOLDER/Acolyte.NET/Libraries/Acolyte.CSharp/bin/Release/*.nupkg" "$env:APPVEYOR_BUILD_FOLDER/Acolyte.NET/Libraries/Acolyte.FSharp/bin/Release/*.nupkg" "$env:APPVEYOR_BUILD_FOLDER/Acolyte.NET/Libraries/Acolyte.NET/bin/Release/*.nupkg"
      }

test:
  assemblies:
    - '**\*.Tests.dll'

after_test:
  # F# tests does not execute at all.
  - ps: dotnet test --configuration $env:configuration --no-build "Acolyte.NET/Tests/Acolyte.FSharp.Tests/Acolyte.FSharp.Tests.fsproj"
  # Check code style.
  - ps: dotnet format Acolyte.NET --severity warn --verbosity diagnostic --verify-no-changes

# Upload all NuGet packages to release assets.
artifacts:
  - path: '**\*.nupkg'
    name: AcolyteNuget

  - path: '$(acolytePackageZip)'
    name: AcolyteZip
    type: zip

# 1. Regenerate AppVeyor Api Key
# https://www.nuget.org/account/apikeys
# 2. Encrypt configuration data
# https://ci.appveyor.com/tools/encrypt
# 3. Paste below

# Deploy from master branch only.
deploy:
  # Deploy to NuGet repository.
  - provider: NuGet
    api_key:
      secure: pnNm4YivoAgvvIjcWESe5vl7LLLxDOf7gKzoYgwthjCw0HR1d8H1xtMLUJOfUpkX
    skip_symbols: false
    artifact: AcolyteNuget
    on:
      branch: master
      configuration: Release

  # Deploy to GitHub Releases.
  - provider: GitHub
    auth_token:
      secure: ex3ZUcCal1DZuXKOFoKSmiAF/NWXttFMYOQEETqrGvIanWZdyP1sesEoOmy3Rvw6
    tag: 'v$(packageVersion)'
    release: 'Acolyte.NET v$(packageVersion)'
    description: 'TODO: write a description.'
    draft: false
    prerelease: false
    artifact: AcolyteZip
    on:
      branch: master
      configuration: Release

pull_requests:
    do_not_increment_build_number: true

nuget:
    disable_publish_on_pr: true
