version: '{build}'
image: Visual Studio 2019

branches:
  only:
    - master
    - develop

configuration:
  - Debug
  - Release

matrix:
  fast_finish: true

before_build:
  - cmd: cd Acolyte.NET
  - cmd: dotnet restore

build:
  verbosity: minimal

test:
  assemblies:
    - '**\*.Tests.dll'

pull_requests:
    do_not_increment_build_number: true

nuget:
    disable_publish_on_pr: true

after_build:
  - dotnet pack "Acolyte.CSharp" -c Release
  - dotnet pack "Acolyte.FSharp" -c Release
  - dotnet pack "Acolyte.NET" -c Release

artifacts:
  - path: Libraries\Acolyte.CSharp\bin\Release\*.nupkg
  - path: Libraries\Acolyte.FSharp\bin\Release\*.nupkg
  - path: Libraries\Acolyte.NET\bin\Release\*.nupkg

deploy:
  - provider: Environment
    name: Acolyte.NET
    on:
      branch: master
      configuration: Release
