version: '{build}'
image: Visual Studio 2019

branches:
  only:
    - master
    - develop

platform:
  - AnyCPU
  - x64
  - x86

configuration:
  - Debug
  - Release

matrix:
  fast_finish: true

before_build:
  - cmd: cd Acolyte.NET
  - cmd: dotnet restore

build:
  verbosity: minimal

test:
  assemblies:
    - '**\*.Tests.dll'

pull_requests:
    do_not_increment_build_number: true

nuget:  
    disable_publish_on_pr: true

artifacts:
  - path: Acolyte.NET\bin\Release\*.nupkg

deploy:  
  - provider: Environment
  name: Acolyte.NET
  on:
    branch: master

