version: '{build}'
image: Visual Studio 2019

branches:
  only:
    - master
    - develop

platform:
  - x64

configuration:
  - Debug
  - Release

matrix:
  fast_finish: true

before_build:
  - cmd: cd ThingAppraiser
  - cmd: dotnet restore

build:
  verbosity: minimal

test:
  assemblies:
    - '**\*.Tests.dll'

# F# tests does not execute at all.
after_test:
  - ps: >-
      if ($env:configuration -eq "Debug")
      {
        dotnet test "C:\projects\thingappraiser\ThingAppraiser\Tests\ThingAppraiser.ContentDirectories.Tests\ThingAppraiser.ContentDirectories.Tests.fsproj" --configuration Debug --no-build
      }
      else
      {
        dotnet test "C:\projects\thingappraiser\ThingAppraiser\Tests\ThingAppraiser.ContentDirectories.Tests\ThingAppraiser.ContentDirectories.Tests.fsproj" --configuration Release --no-build
      }

pull_requests:
    do_not_increment_build_number: true

nuget:  
    disable_publish_on_pr: true
