environment:
  packageVersion: 2.1.0
  acolytePackageZip: 'Acolyte.NET.$(packageVersion).zip'

version: '$(packageVersion).{build}'
image: Visual Studio 2019

# Do not build on tags (GitHub, Bitbucket, GitLab, Gitea).
skip_tags: true

shallow_clone: true

dotnet_csproj:
  patch: true
  file: '**\*.csproj;**\*.fsproj'
  assembly_version: '$(packageVersion)'
  file_version: '$(packageVersion)'
  version: '$(packageVersion)'

branches:
  only:
    - master
    - develop

configuration:
  - Debug
  - Release

matrix:
  fast_finish: true

install:
  - ps: dotnet tool update -g dotnet-format

before_build:
  - ps: cd Acolyte.NET
  - ps: dotnet restore

build:
  verbosity: minimal

after_build:
  - ps: >-
      if (($env:configuration -eq "Release") -and ($env:APPVEYOR_REPO_BRANCH -eq "master"))
      {
        dotnet pack --configuration Release --no-build "../Acolyte.NET"
        7z a -tzip "$env:APPVEYOR_BUILD_FOLDER/$env:acolytePackageZip" "$env:APPVEYOR_BUILD_FOLDER/Acolyte.NET/Libraries/Acolyte.CSharp/bin/Release/*.nupkg" "$env:APPVEYOR_BUILD_FOLDER/Acolyte.NET/Libraries/Acolyte.FSharp/bin/Release/*.nupkg" "$env:APPVEYOR_BUILD_FOLDER/Acolyte.NET/Libraries/Acolyte.NET/bin/Release/*.nupkg"
      }

test:
  assemblies:
    - '**\*.Tests.dll'

after_test:
  # F# tests does not execute at all.
  - ps: dotnet test --configuration $env:configuration --no-build "Tests/Acolyte.FSharp.Tests/Acolyte.FSharp.Tests.fsproj"
  # Check code style.
  - ps: dotnet format "Acolyte.NET.sln" --fix-whitespace --fix-style warn --check --verbosity diagnostic

  # Upload all NuGet packages to release assets.
artifacts:
  - path: '**\*.nupkg'
    name: AcolyteNuget

  - path: '$(acolytePackageZip)'
    name: AcolyteZip
    type: zip

# 1. Regenerate AppVeyor Api Key
# https://www.nuget.org/account/apikeys
# 2. Encrypt configuration data
# https://ci.appveyor.com/tools/encrypt
# 3. Paste below

# Deploy from master branch only.
deploy:
  # Deploy to NuGet repository.
  - provider: NuGet
    api_key:
      secure: hnKm9eh2iZree0QLhfMG6dkeBzGsJ3UNZpHbddhSB99FuaZxlh8Z+FxHX3c/l3Re
    skip_symbols: false
    artifact: AcolyteNuget
    on:
      branch: master
      configuration: Release

  # Deploy to GitHub Releases.
  - provider: GitHub
    auth_token:
      secure: ex3ZUcCal1DZuXKOFoKSmiAF/NWXttFMYOQEETqrGvIanWZdyP1sesEoOmy3Rvw6
    tag: 'v$(packageVersion)'
    release: 'Acolyte.NET v$(packageVersion)'
    description: 'TODO: write a description.'
    draft: false
    prerelease: false
    artifact: AcolyteZip
    on:
      branch: master
      configuration: Release

pull_requests:
    do_not_increment_build_number: true

nuget:
    disable_publish_on_pr: true
